dist: trusty
sudo: required

language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cmake3
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libyaml-cpp-dev
      - libfftw3-dev
      - libgd2-noxpm-dev
      - libfreetype6-dev
      - libasound-dev
      - libhackrf-dev
      - librtlsdr-dev
      - libusb-1.0-0-dev
      - librtfilter-dev
      - libssh-dev
      - libcurl4-openssl-dev

before_install:
  - ./scripts/install-libhackrf.sh

script:
  - mkdir -p build && cd build && cmake .. && cmake --build .
